### ISSUE TITLE
1.0 Umbrella bug

### ISSUE THREAD

**Issue by tolmasky** [runkitdev/lithograph#9]
- [ ] Documentation
- [ ] Generate HTML Results
- [ ] ~Flaky Test Support~
- [ ] Allow running without launching Chrome instances?

**Comment by tolmasky** [comment]
Closed in favor of milestone: https://github.com/runkitdev/lithograph/milestone/1
